### ISSUE TITLE
Highlight identifiers within template literals please

### ISSUE THREAD

**Issue by henrahmagix** [bcj/JSyntax#4]
See the identifiers in `${lang}` and `${i18nDir}` highlighted apart from the rest of the literal content. I'd love to see that in this syntax as used by GitHub please!

## Expected

Screenshot from Sublime Text 3 
![image](https://user-images.githubusercontent.com/1429026/27132698-bb136b5c-5107-11e7-9800-f542fa1dbc0d.png)

with inbuilt JavaScript syntax, no packages installed that are known to affect this (I might be wrong)
![image](https://user-images.githubusercontent.com/1429026/27132709-c4b2e408-5107-11e7-8eb8-79c844ad3c0c.png)

## Actual

Code
```js
const locales = ['en-gb', 'de-de'];
locales.forEach((lang) => {
    const loaderId = `angular-i18n-loader_${lang}`;
    i18nFiles[lang] = `<%= config.paths.bowerDir %>/${i18nDir}/angular-locale_${lang}.js`;
    concatLocales[`${lang}-locale`] = {
        src: [
            `<%= config.paths.i18nFiles["${lang}"] %>`,
            '<%= config.paths.srcScriptsDir %>/start-app.js'
        ],
        dest: `<%= config.paths.compiledScriptsDir %>/<%= config.paths.i18nDir %>/${loaderId}.js`
    };
    i18nLoaders.push(`
        <!-- build:i18njs scripts/${i18nDir}/${loaderId}.js -->
        <!-- Include a src reference for the i18n file so the path can be rewritten -->
        <!-- by usemin and filerev and found by locale-loader in both dev and build. -->
        <!-- What's written here must be exactly what usemin replaces with build:i18njs -->
        <!-- so dev and build are identical apart from the revved filename. -->
        <a style="display:none;" id="${loaderId}" href="scripts/${i18nDir}/${loaderId}.js"></a>
        <!-- endbuild -->
    `);
});
```

Screenshot from above code block at time of submission (taken from Preview)
![image](https://user-images.githubusercontent.com/1429026/27133539-5f65fc40-510a-11e7-9e65-6916176e8839.png)

**Comment by henrahmagix** [comment]
I've just tested in Lightshow and I can see a very slight blue colour on the strings, quoted `' '` and templated `` ` ` ``, whilst the `${}` bits are black, but that's not showing here on GitHub.

[Test link here](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.js&grammar_url=&grammar_text=&code_source=from-text&code_url=&code=const+locales+%3D+%5B%27en-gb%27%2C+%27de-de%27%5D%3B%0D%0Alocales.forEach%28%28lang%29+%3D%3E+%7B%0D%0A++++const+loaderId+%3D+%60angular-i18n-loader_%24%7Blang%7D%60%3B%0D%0A++++i18nFiles%5Blang%5D+%3D+%60%3C%25%3D+config.paths.bowerDir+%25%3E%2F%24%7Bi18nDir%7D%2Fangular-locale_%24%7Blang%7D.js%60%3B%0D%0A++++concatLocales%5B%60%24%7Blang%7D-locale%60%5D+%3D+%7B%0D%0A++++++++src%3A+%5B%0D%0A++++++++++++%60%3C%25%3D+config.paths.i18nFiles%5B%22%24%7Blang%7D%22%5D+%25%3E%60%2C%0D%0A++++++++++++%27%3C%25%3D+config.paths.srcScriptsDir+%25%3E%2Fstart-app.js%27%0D%0A++++++++%5D%2C%0D%0A++++++++dest%3A+%60%3C%25%3D+config.paths.compiledScriptsDir+%25%3E%2F%3C%25%3D+config.paths.i18nDir+%25%3E%2F%24%7BloaderId%7D.js%60%0D%0A++++%7D%3B%0D%0A++++i18nLoaders.push%28%60%0D%0A++++++++%3C%21--+build%3Ai18njs+scripts%2F%24%7Bi18nDir%7D%2F%24%7BloaderId%7D.js+--%3E%0D%0A++++++++%3C%21--+Include+a+src+reference+for+the+i18n+file+so+the+path+can+be+rewritten+--%3E%0D%0A++++++++%3C%21--+by+usemin+and+filerev+and+found+by+locale-loader+in+both+dev+and+build.+--%3E%0D%0A++++++++%3C%21--+What%27s+written+here+must+be+exactly+what+usemin+replaces+with+build%3Ai18njs+--%3E%0D%0A++++++++%3C%21--+so+dev+and+build+are+identical+apart+from+the+revved+filename.+--%3E%0D%0A++++++++%3Ca+style%3D%22display%3Anone%3B%22+id%3D%22%24%7BloaderId%7D%22+href%3D%22scripts%2F%24%7Bi18nDir%7D%2F%24%7BloaderId%7D.js%22%3E%3C%2Fa%3E%0D%0A++++++++%3C%21--+endbuild+--%3E%0D%0A++++%60%29%3B%0D%0A%7D%29%3B)
![image](https://user-images.githubusercontent.com/1429026/27133355-b6f46448-5109-11e7-8c6d-4ee324428953.png)

**Comment by tikkanz** [comment]
You seem to be interested in Sublime Text syntax highlighting for Javascript however this repository provides support for the J language.
Are you sure you're commenting on the correct repository?

**Comment by henrahmagix** [comment]
Ack! Sorry! Thanks for letting me know =)
